name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:$GITHUB_SHA .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:$GITHUB_SHA

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker stop cicd-demo || true
          docker rm cicd-demo || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-demo:$GITHUB_SHA
          docker run -d -p 80:80 --name cicd-demo ${{ secrets.DOCKER_USERNAME }}/cicd-demo:$GITHUB_SHA
